#!/bin/sh

set -e

ARCHITECTURE="$(basename $PWD)"
ARCH="${ARCHITECTURE:=$(dpkg --print-architecture)}"

# if [ ! -e "./cache" ]; then
#     ln -s ../../../cache cache
# fi

if [ ! -e "/usr/share/live/build/data/debian-cd/cybint" ]; then
    ln -s /usr/share/live/build/data/debian-cd/squeeze /usr/share/live/build/data/debian-cd/cybint
fi

if [ ! -e "/usr/share/debootstrap/scripts/cybint" ]; then
cat >> /usr/share/debootstrap/scripts/cybint <<EOL
mirror_style release
download_style apt
finddebs_style from-indices
variants - buildd fakechroot minbase
keyring /usr/share/keyrings/cybint-archive-keyring.gpg

# include common settings
if [ -e "$DEBOOTSTRAP_DIR/scripts/debian-common" ]; then
 . "$DEBOOTSTRAP_DIR/scripts/debian-common"
elif [ -e /debootstrap/debian-common ]; then
 . /debootstrap/debian-common
elif [ -e "$DEBOOTSTRAP_DIR/debian-common" ]; then
 . "$DEBOOTSTRAP_DIR/debian-common"
else
 error 1 NOCOMMON "File not found: debian-common"
fi
EOL
fi



lb config noauto \
	--clean \
	--color \
	-d cybint \
	--utc-time true \
	--architectures $ARCH \
	--ignore-system-defaults \
	--mode debian \
	--updates false \
	--security false \
	--apt-secure false \
	--apt-recommends false \
	--debian-installer live \
	--debian-installer-gui false \
	--image-name "cybint-live" \
	--iso-application "CYBINT Linux" \
	--iso-publisher "CYBINT Linux" \
	--iso-volume "CYBINT Live" \
	--source-images iso \
	--linux-packages "linux-image linux-headers" \
	--bootappend-live "boot=live username=cybint hostname=cybint components quiet splash noeject" \
    --keyring-packages "cybint-archive-keyring" \
    --archive-areas "main" \
    --debian-installer-distribution cybint \
	--mirror-binary "http://repo.cybint-linux.com/cybint" \
    --mirror-bootstrap "http://repo.cybint-linux.com/cybint" \
    --mirror-chroot "http://repo.cybint-linux.com/cybint" \
    --mirror-debian-installer "http://repo.cybint-linux.com/cybint" \
    --parent-archive-areas "main" \
    --parent-debian-installer-distribution cybint \
    --parent-distribution cybint \
    --parent-distribution-chroot cybint \
    --parent-distribution-binary cybint \
    --parent-mirror-binary "http://repo.cybint-linux.com/cybint" \
    --parent-mirror-bootstrap "http://repo.cybint-linux.com/cybint" \
    --parent-mirror-chroot "http://repo.cybint-linux.com/cybint" \
    --parent-mirror-debian-installer "http://repo.cybint-linux.com/cybint" \
	--source false \
"${@}"

	# --parent-mirror-chroot-security  "http://security.debian.org/" \
	# --parent-mirror-bootstrap "http://repo.cybint-linux.com/cybint" \
	# --parent-mirror-chroot "http://repo.cybint-linux.com/cybint" \

	# --bootappend-live "boot=live components quiet splash noeject" \
	# --bootappend-live-failsafe "boot=live components noeject memtest noapic noapm nodma nomce nolapic nomodeset nosmp nosplash vga=normal username=cybint" \
	# --bootappend-install "net.ifnames=0" \


    #    lb config
    #         [--apt apt|apt-get|aptitude]
    #         [--apt-ftp-proxy URL]
    #         [--apt-http-proxy URL]
    #         [--apt-indices true|false]
    #         [--apt-options OPTION|"OPTIONS"]
    #         [--apt-pipeline DEPTH]
    #         [--apt-recommends true|false]
    #         [--apt-secure true|false]
    #         [--apt-source-archives true|false]
    #         [--aptitude-options OPTION|"OPTIONS"]
    #         [-a|--architecture ARCHITECTURE]
    #         [--archive-areas ARCHIVE_AREA|"ARCHIVE_AREAS"]
    #         [--backports true|false]
    #         [--binary-filesystem fat16|fat32|ext2|ext3|ext4|ntfs]
    #         [-b|--binary-image iso|iso-hybrid|netboot|tar|hdd]
    #         [--bootappend-install PARAMETER|"PARAMETERS"]
    #         [--bootappend-live PARAMETER|"PARAMETERS"]
    #         [--bootappend-live-failsafe PARAMETER|"PARAMETERS"]
    #         [--bootloaders grub-legacy|grub-pc|syslinux|grub-efi|"BOOTLOADERS"]
    #         [--bootstrap-qemu-arch ARCH]
    #         [--bootstrap-qemu-exclude PACKAGE|"PACKAGES"]
    #         [--bootstrap-qemu-static PATH]
    #         [--breakpoints]
    #         [--build-with-chroot true|false]
    #         [--cache true|false]
    #         [--cache-indices true|false]
    #         [--cache-packages true|false]
    #         [--cache-stages STAGE|"STAGES"]
    #         [--checksums md5|sha1|sha224|sha256|sha384|sha512|none]
    #         [--chroot-filesystem ext2|ext3|ext4|squashfs|jffs2|none]
    #         [--chroot-squashfs-compression-level LEVEL]
    #         [--chroot-squashfs-compression-type gzip|lzma|lzo|lz4|xz|zstd]
    #         [--clean]
    #         [--color]
    #         [--compression bzip2|gzip|lzip|xz|none]
    #         [-c|--conffile FILE]
    #         [--config GIT_URL::GIT_BRANCH]
    #         [--debconf-frontend dialog|editor|noninteractive|readline]
    #         [--debconf-priority low|medium|high|critical]
    #         [--debian-installer cdrom|netinst|netboot|businesscard|live|none]
    #         [--debian-installer-distribution daily|CODENAME]
    #         [--debian-installer-gui true|false]
    #         [--debian-installer-preseedfile FILE|URL]
    #         [--debootstrap-options OPTION|"OPTIONS"]
    #         [--debootstrap-script SCRIPT]
    #         [--debug]
    #         [-d|--distribution CODENAME]
    #         [--distribution-chroot CODENAME]
    #         [--distribution-binary CODENAME]
    #         [--dm-verity]
    #         [--dm-verity-fec NB_ROOTS]
    #         [--dm-verity-sign SIGN_SCRIPT]
    #         [--dump]
    #         [--firmware-binary true|false]
    #         [--firmware-chroot true|false]
    #         [--force]
    #         [--gzip-options OPTION|"OPTIONS"]
    #         [--hdd-label LABEL]
    #         [--hdd-partition-start START]
    #         [--hdd-size SIZE]
    #         [--ignore-system-defaults]
    #         [--image-name NAME]
    #         [--initramfs none|live-boot]
    #         [--initramfs-compression bzip2|gzip|lzma]
    #         [--initsystem sysvinit|systemd|none]
    #         [--interactive true|shell|x11|xnest|false]
    #         [--iso-application NAME]
    #         [--iso-preparer NAME]
    #         [--iso-publisher NAME]
    #         [--iso-volume NAME]
    #         [--jffs2-eraseblock SIZE]
    #         [--keyring-packages PACKAGE|"PACKAGES"]
    #         [-k|--linux-flavours FLAVOUR|"FLAVOURS"]
    #         [--linux-packages PACKAGE|"PACKAGES"]
    #         [--loadlin true|false]
    #         [--memtest memtest86+|memtest86|none]
    #         [--mirror-binary URL]
    #         [--mirror-binary-security URL]
    #         [--mirror-bootstrap URL]
    #         [--mirror-chroot URL]
    #         [--mirror-chroot-security URL]
    #         [--mirror-debian-installer URL]
    #         [--mode debian]
    #         [--net-tarball true|false]
    #         [--no-color]
    #         [--onie true|false]
    #         [--onie-kernel-cmdline OPTION|"OPTIONS"]
    #         [--parent-archive-areas ARCHIVE_AREA|"ARCHIVE_AREAS"]
    #         [--parent-debian-installer-distribution daily|CODENAME]
    #         [--parent-distribution CODENAME]
    #         [--parent-distribution-chroot CODENAME]
    #         [--parent-distribution-binary CODENAME]
    #         [--parent-mirror-binary URL]
    #         [--parent-mirror-binary-security URL]
    #         [-m|--parent-mirror-bootstrap URL]
    #         [--parent-mirror-chroot URL]
    #         [--parent-mirror-chroot-security URL]
    #         [--parent-mirror-debian-installer URL]
    #         [--quiet]
    #         [--security true|false]
    #         [--source true|false]
    #         [-s|--source-images iso|netboot|tar|hdd|"IMAGES"]
    #         [--swap-file-path PATH]
    #         [--swap-file-size MB]
    #         [--system live|normal]
    #         [--uefi-secure-boot auto|enable|disable]
    #         [--updates true|false]
    #         [--utc-time true|false]
    #         [--validate]
    #         [--verbose]
    #         [--win32-loader true|false]
    #         [--zsync true|false]
