#!/bin/sh


# Avoid configuring multiple times in case persistence is enabled
if [ -e /var/lib/live/config/cybint-user-setup ]; then
    exit 0
fi

# Set "cybint" as password for the user cybint
# Use 'openssl passwd' to generate the password
usermod -p 'Vz5x7dUAVLpKE' cybint


# Remember that this script has been run
touch /var/lib/live/config/cybint-user-setup
